# Generated by Django 6.0.1 on 2026-02-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100)),
                ('Bedroom', models.IntegerField()),
                ('pool', models.BooleanField()),
            ],
            options={
                'db_table': 'Property',
            },
        ),
    ]
