# Generated by Django 6.0.1 on 2026-02-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoivesName', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Moives',
            },
        ),
    ]
