# Generated by Django 6.0.1 on 2026-02-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='RevieweeId',
        ),
    ]
