# Generated by Django 6.0.1 on 2026-02-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_bid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='AdminId',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='BuyerId',
        ),
        migrations.RemoveField(
            model_name='category',
            name='CategoryId',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='SellerId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserId',
        ),
        migrations.AddField(
            model_name='admin',
            name='Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.AddField(
            model_name='seller',
            name='Name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
    ]
