# Generated by Django 6.0.1 on 2026-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServicesName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Duration', models.IntegerField(help_text='Duration in days')),
                ('Is_Activate', models.BooleanField()),
                ('Created_At', models.DateField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
    ]
