# Generated by Django 6.0.1 on 2026-02-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Starting_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Reserve_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('Status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], max_length=20)),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerRating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.IntegerField()),
                ('CategoryName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerRating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('TotalItemsSold', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('UserName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('RegistrationDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BidTime', models.DateTimeField()),
                ('Status', models.CharField(max_length=100)),
                ('AuctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='test_app.auction')),
                ('BuyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='test_app.buyer')),
            ],
            options={
                'db_table': 'Bid',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='CategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.category'),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURB', 'Refurbished')], max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='test_app.category')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='ItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.items'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('UPI', 'UPI'), ('NETBANK', 'Net Banking')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='test_app.auction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='test_app.buyer')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='SellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='SellerId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BID_PLACED', 'Bid Placed'), ('OUTBID', 'Outbid'), ('AUCTION_ENDED', 'Auction Ended'), ('PAYMENT', 'Payment'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.auction')),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='test_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='BuyerId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('SUPER', 'Super Admin'), ('MOD', 'Moderator'), ('SUB', 'Sub Admin')], default='MOD', max_length=50)),
                ('AdminId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddedDate', models.DateTimeField()),
                ('AuctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='test_app.auction')),
                ('BuyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='test_app.buyer')),
            ],
            options={
                'db_table': 'WatchList',
            },
        ),
    ]
