# Generated by Django 6.0.1 on 2026-02-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
                ('ReviewDate', models.DateTimeField()),
                ('AuctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.auction')),
                ('RevieweeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='test_app.user')),
                ('ReviewerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='test_app.user')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
