# Generated by Django 6.0.1 on 2026-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_remove_review_revieweeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='Status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('OUTBID', 'Outbid'), ('WINNING', 'Winning'), ('LOST', 'Lost')], max_length=100),
        ),
    ]
