# Generated by Django 6.0.1 on 2026-02-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auction_current_price_auction_winner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'db_table': 'ActivityLog',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.auction')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
            options={
                'db_table': 'Dispute',
            },
        ),
    ]
