# Generated by Django 6.0.1 on 2026-02-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='StudentProfile1',
        ),
        migrations.AlterModelTable(
            name='studentprofile1',
            table='StudentProfile1',
        ),
    ]
