# Generated by Django 6.0.1 on 2026-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
