# Generated by Django 6.0.1 on 2026-02-18 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyer',
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='product_auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default=True)),
            ],
            options={
                'verbose_name': 'Product Auction',
                'verbose_name_plural': 'Product Auction',
                'db_table': 'product_auction',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Seller',
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
                ('salary', models.PositiveBigIntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.buyer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.product_auction')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bid',
                'db_table': 'bid',
            },
        ),
        migrations.AddField(
            model_name='product_auction',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.seller'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('Categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbies', models.CharField(choices=[('Reading', 'Reading'), ('Sports', 'Sports'), ('Music', 'Music'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Gaming', 'Gaming'), ('Art', 'Art'), ('Dancing', 'Dancing'), ('Photography', 'Photography'), ('Writing', 'Writing')], max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'StudentProfile1',
            },
        ),
        migrations.CreateModel(
            name='passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passport',
                'db_table': 'passport',
            },
        ),
    ]
