# Generated by Django 6.0.1 on 2026-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_color_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
