# Generated by Django 6.0.1 on 2026-02-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_teacher_email_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbies', models.CharField(choices=[('Reading', 'Reading'), ('Sports', 'Sports'), ('Music', 'Music'), ('Traveling', 'Traveling'), ('Cooking', 'Cooking'), ('Gaming', 'Gaming'), ('Art', 'Art'), ('Dancing', 'Dancing'), ('Photography', 'Photography'), ('Writing', 'Writing')], max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'StudentProfile',
            },
        ),
    ]
