# Generated by Django 6.0.1 on 2026-02-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_user_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='product_auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('color', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.seller')),
            ],
            options={
                'db_table': 'product_auction',
            },
        ),
    ]
