# Generated by Django 6.0.1 on 2026-02-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_seller_product_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.product_auction')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.buyer')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
    ]
