# Generated by Django 6.0.1 on 2026-02-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_studentprofile_studentprofile1_and_more'),
        ('student', '0011_buyer_bid'),
    ]

    operations = [
    ]
